EXPERIMENT_NAME: 'eval-baseline-robotcar'

SYSTEM:
  BENCHMARK: False

LOAD:
  CHECKPOINT_PATH: 
  SPLIT_FILES_PATH: 

DATASET:
  DATAROOT: './datasets/robotcar/'
  NAME: 'robotcar'
  ORIGINAL_SIZE:
    HEIGHT: 960
    WIDTH: 1280
  WEATHER:
    VAL: ['day-clear', 'night-clear']
    TEST: ['day-clear', 'night-clear']
  AUGMENTATION:
    CROP:
      HEIGHT: 768
      WIDTH: 1280
    RESIZE:
      WIDTH: 544

EVALUATION:
  BATCH_SIZE: 1
  DEPTH:
    MAX_DEPTH: 50.0
  USE_VALIDATION_SET: False
  SAVE:
    QUANTITATIVE_RES_PATH: './results/quantitative/robotcar/test/'
