EXPERIMENT_NAME: 'eval-ACDepth-nuscenes'

SYSTEM:
  BENCHMARK: False

LOAD:
  CHECKPOINT_PATH: ./checkpoints/ACDepth_nuScenes.ckpt

DATASET:
  AUGMENTATION:
    NORMALIZE:
      MODE: 'Daytime'

EVALUATION:
  BATCH_SIZE: 1
  SAVE:
    QUANTITATIVE_RES_PATH: './results/quantitative/nuscenes/val'
    QUALITATIVE_RES_PATH: './results/qualitative/nuscenes/val/ACDepth'
    RGB: False
    DEPTH:
      GT: True
      PRED: False

LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
  CONTRAST_WEIGHT: 0.02
  RANK_WEIGHT: 0.01
