EXPERIMENT_NAME: 'eval-ACDepth-robotcar'

SYSTEM:
  BENCHMARK: False

LOAD:
  CHECKPOINT_PATH: ./checkpoints/ACDepth_RobotCar.ckpt
  SPLIT_FILES_PATH: './datasets/robotcar/dataset/splits'

DATASET:
  DATAROOT: './datasets/robotcar/'
  NAME: 'robotcar'
  ORIGINAL_SIZE:
    HEIGHT: 960
    WIDTH: 1280
  WEATHER:
    VAL: ['day-clear', 'night-clear']
    TEST: ['day-clear', 'night-clear']
  AUGMENTATION:
    CROP:
      HEIGHT: 768
      WIDTH: 1280
    RESIZE:
      WIDTH: 544
    NORMALIZE:
      MODE: 'Daytime'
      DAYTIME:
        DAY:
          MEAN: 0.5758
          STD: 0.319
        NIGHT:
          MEAN: 0.2471
          STD: 0.2627

EVALUATION:
  BATCH_SIZE: 1
  DEPTH:
    MAX_DEPTH: 50.0
  USE_VALIDATION_SET: False
  SAVE:
    QUANTITATIVE_RES_PATH: './results/quantitative/robotcar/test/'
    QUALITATIVE_RES_PATH: './results/qualitative/robotcar/val/ACDepth'
    RGB: False
    DEPTH:
      GT: True
      PRED: False
      
LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
  CONTRAST_WEIGHT: 0.02
  RANK_WEIGHT: 0.01
