EXPERIMENT_NAME: 'test-ACDepth-robotcar'

LOAD:
  CHECKPOINT_PATH: 
DATASET:
  AUGMENTATION:
    CROP:
      HEIGHT: 768
      WIDTH: 1280
    RESIZE:
      WIDTH: 544
    NORMALIZE:
      MODE: 'Image' 


LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
  CONTRAST_WEIGHT: 0.02
  RANK_WEIGHT: 0.01
