EXPERIMENT_NAME: 'test-ACDepth-nuscenes'

LOAD:
  CHECKPOINT_PATH: 
DATASET:
  AUGMENTATION:
    NORMALIZE:
      MODE: 'Image' 

LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
  CONTRAST_WEIGHT: 0.02
  RANK_WEIGHT: 0.01
