EXPERIMENT_NAME: 'train-baseline-robotcar'

SAVE:
  CHECKPOINT_PATH: 'log/checkpoints/robotcar_baseline'
  TOP_K: -1

LOAD:
  SPLIT_FILES_PATH: './datasets/robotcar/splits'
  FILTER_FILES_PATH: './datasets/robotcar/filter'

DATASET:
  AUGMENTATION:
    COLOR_JITTER:
      SAMPLE_KEYS: ['color_aug', 'color_aug_pose']
    GAUSSIAN_NOISE:
      SAMPLE_KEYS: ['color_aug', 'color_aug_pose']
    GAUSSIAN_BLUR:
      SAMPLE_KEYS: ['color_aug', 'color_aug_pose']
  TEMP_CONTEXT: [0, -1, 1]

  DATAROOT: './datasets/robotcar/'
  NAME: 'robotcar'
  ORIGINAL_SIZE:
    HEIGHT: 960
    WIDTH: 1280
  WEATHER:
    VAL: ['day-clear', 'night-clear']
    TEST: ['day-clear', 'night-clear']
  AUGMENTATION:
    CROP:
      HEIGHT: 768
      WIDTH: 1280
    RESIZE:
      WIDTH: 544
